import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

// ── CSP — no Razorpay, UPI deep links are native device redirects (no CSP needed) ──

const DEV_CSP = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com data:",
  // localhost:8080 = Spring Boot (proxied) serving /uploads/ product images
  "img-src 'self' data: blob: http://localhost:8080 http://localhost:*",
  "frame-src 'self'",
  "connect-src 'self' ws://localhost:* wss://localhost:*",
  "worker-src 'self' blob:",
].join('; ');

const PROD_CSP = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com data:",
  "img-src 'self' data: blob:",
  "frame-src 'self'",
  // connect-src must allow the backend API origin in production
  // If your API is on a different domain, add it here or set VITE_API_BASE_URL
  "connect-src 'self'",
  "worker-src 'self' blob:",
].join('; ');

// ── Plugin: write Netlify _headers after build ────────────────────────────────
function writeProductionHeaders() {
  return {
    name: 'write-production-headers',
    closeBundle() {
      const netlifyHeaders = [
        '# Auto-generated by vite.config.js — do not edit manually',
        '/*',
        `  Content-Security-Policy: ${PROD_CSP}`,
        `  X-Content-Type-Options: nosniff`,
        `  X-Frame-Options: SAMEORIGIN`,
        `  Referrer-Policy: strict-origin-when-cross-origin`,
        `  Permissions-Policy: camera=(), microphone=(), geolocation=()`,
        '',
      ].join('\n');

      const outDir = path.resolve(__dirname, 'dist');
      if (fs.existsSync(outDir)) {
        fs.writeFileSync(path.join(outDir, '_headers'), netlifyHeaders);
        console.log('[vite-csp] Wrote dist/_headers');
      }
    },
  };
}

export default defineConfig(({ mode }) => ({
  plugins: [
    react(),
    ...(mode === 'production' ? [writeProductionHeaders()] : []),
  ],

  server: {
    port: 3000,
    headers: {
      'Content-Security-Policy': DEV_CSP,
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'SAMEORIGIN',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    },
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        secure: false,
        configure: (proxy) => {
          proxy.on('error', (err) => {
            console.error('[Vite Proxy] Backend unreachable:', err.message);
          });
          proxy.on('proxyReq', (_, req) => {
            console.log('[Vite Proxy] →', req.method, req.url);
          });
        },
      },
      '/uploads': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        secure: false,
      },
    },
  },

  build: {
    sourcemap: false,
    minify: 'esbuild',
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ['react', 'react-dom', 'react-router-dom'],
        },
      },
    },
  },
}))
